###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine

    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "8021:8025"

    redis:
      image: redis:6.2.0-alpine
      container_name: kinex_redis
      restart: always
      ports:
        - "1001:6379"
      volumes:
        - redis-data:/data

    mysql:
      image: mysql:8.0
      restart: always
      container_name: kinex_mysql
      working_dir: /application
      volumes:
        # - .:/application/mystore
        - db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=magefive
        - MYSQL_DATABASE=magefive
        #- MYSQL_USER=magefive
        - MYSQL_PASSWORD=magefive
      command: ["--log_bin_trust_function_creators=1"]
      ports:
        - "8012:3306"

    clickhouse:
      image: yandex/clickhouse-server:latest

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
      environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        #- discovery.seed_hosts=es02,es03
        - cluster.initial_master_nodes=elasticsearch
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
        # - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - 8001:9200
    
    webserver:
      image: nginx:alpine
      #container_name: kinex_nginx_server
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8300:80"
        - "443:443"
        - "32824:22"
      links:
        - mysql:mysql
        - elasticsearch:elasticsearch
        - redis:redis
        - mailhog:mailhog
        - memcached:memcached
      depends_on:
        - mysql
        - elasticsearch
        - redis
        - mailhog
        - memcached

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      tty: true
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/opt/bitnami/php/etc/conf.d/99-overrides.ini
        - ./node_modules:/node_modules
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        MYSQL_USERNAME: kinex
        MYSQL_ROOT_PASSWORD: kinex
        PMA_HOST: mysql
      ports:
        - 8005:80
      links:
        - mysql:mysql
        - elasticsearch:elasticsearch
        - redis:redis
        - mailhog:mailhog
        - memcached:memcached
      depends_on:
        - mysql
        - elasticsearch
        - redis
        - mailhog
        - memcached
    # custom-node:
    #   build: app-npm
    #   container_name: custom-node
    #   working_dir: /application
    #   volumes:
    #     - .:/application
    #     #- /application/node_modules
    #   tty: true
volumes:
  data01:
    external: false
  # elasticsearch-data:
  #   driver: local
  db-data:
    external: false
  redis-data:
    external: false